/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vn.paracel.pos.gui.keyboard;

import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author thanhchatvn
 */
public class Keyboard extends javax.swing.JFrame {
    private static Keyboard instance = null;
    private JTextField activeTextField ;
    private String fulltext;
    //private boolean caps = false;
    String[] listButton;
    /**
     * Creates new form Keyboard
     */
    public Keyboard() {
        initComponents();
    }
    
    public static Keyboard getInstance() {
        if(instance == null) {
            instance = new Keyboard();
        }
        return instance;
    }
    
 
    //contructor
    public void Keyboard() {
        initComponents();
    }

    public JTextField getActiveTextField() {
        return activeTextField;
    }

    public void setActiveTextField(JTextField activeTextField) {
        this.activeTextField = activeTextField;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jButton26 = new javax.swing.JButton();
        jButton27 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        bU = new javax.swing.JButton();
        bE = new javax.swing.JButton();
        but4 = new javax.swing.JButton();
        bW = new javax.swing.JButton();
        bY = new javax.swing.JButton();
        bR = new javax.swing.JButton();
        bT = new javax.swing.JButton();
        bJ = new javax.swing.JButton();
        bK = new javax.swing.JButton();
        bL = new javax.swing.JButton();
        but5 = new javax.swing.JButton();
        bMove = new javax.swing.JButton();
        bI = new javax.swing.JButton();
        bO = new javax.swing.JButton();
        bP = new javax.swing.JButton();
        bQ = new javax.swing.JButton();
        but3 = new javax.swing.JButton();
        but6 = new javax.swing.JButton();
        bC = new javax.swing.JButton();
        bV = new javax.swing.JButton();
        bZ = new javax.swing.JButton();
        bX = new javax.swing.JButton();
        bShift = new javax.swing.JButton();
        bCaps = new javax.swing.JButton();
        but7 = new javax.swing.JButton();
        bSpace = new javax.swing.JButton();
        bA = new javax.swing.JButton();
        bS = new javax.swing.JButton();
        bG = new javax.swing.JButton();
        bH = new javax.swing.JButton();
        bD = new javax.swing.JButton();
        bF = new javax.swing.JButton();
        but8 = new javax.swing.JButton();
        bN = new javax.swing.JButton();
        bB = new javax.swing.JButton();
        bM = new javax.swing.JButton();
        bEnter = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b0 = new javax.swing.JButton();
        bBackSpace = new javax.swing.JButton();
        but1 = new javax.swing.JButton();
        but2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jButton14.setText("`");

        jButton17.setText("1");

        jButton18.setText("2");

        jButton19.setText("3");

        jButton20.setText("4");

        jButton21.setText("5");

        jButton22.setText("6");

        jButton23.setText("7");

        jButton24.setText("8");

        jButton25.setText("9");

        jButton26.setText("0");

        jButton27.setText("-");

        jButton28.setText("=");

        jButton29.setText("\\");

            jButton30.setText("BackSpace");

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jButton30, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton14)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton27, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton29, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton30))
            );

            setAlwaysOnTop(true);
            setBackground(java.awt.Color.cyan);
            setUndecorated(true);

            bU.setBackground(java.awt.SystemColor.text);
            bU.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bU.setText("u");
            bU.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bUActionPerformed(evt);
                }
            });

            bE.setBackground(java.awt.SystemColor.text);
            bE.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bE.setText("e");
            bE.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bEActionPerformed(evt);
                }
            });

            but4.setBackground(java.awt.SystemColor.text);
            but4.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but4.setText("]");
            but4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but4ActionPerformed(evt);
                }
            });

            bW.setBackground(java.awt.SystemColor.text);
            bW.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bW.setText("w");
            bW.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bWActionPerformed(evt);
                }
            });

            bY.setBackground(java.awt.SystemColor.text);
            bY.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bY.setText("y");
            bY.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bYActionPerformed(evt);
                }
            });

            bR.setBackground(java.awt.SystemColor.text);
            bR.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bR.setText("r");
            bR.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bRActionPerformed(evt);
                }
            });

            bT.setBackground(java.awt.SystemColor.text);
            bT.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bT.setText("t");
            bT.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bTActionPerformed(evt);
                }
            });

            bJ.setBackground(java.awt.SystemColor.text);
            bJ.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bJ.setText("j");
            bJ.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bJActionPerformed(evt);
                }
            });

            bK.setBackground(java.awt.SystemColor.text);
            bK.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bK.setText("k");
            bK.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bKActionPerformed(evt);
                }
            });

            bL.setBackground(java.awt.SystemColor.text);
            bL.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bL.setText("l");
            bL.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bLActionPerformed(evt);
                }
            });

            but5.setBackground(java.awt.SystemColor.text);
            but5.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but5.setText(";");
            but5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but5ActionPerformed(evt);
                }
            });

            bMove.setBackground(java.awt.SystemColor.text);
            bMove.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bMove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/paracel/pos/images/btnback.png"))); // NOI18N
            bMove.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
                public void mouseMoved(java.awt.event.MouseEvent evt) {
                    bMoveMouseMoved(evt);
                }
            });
            bMove.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bMoveActionPerformed(evt);
                }
            });
            bMove.addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
                public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
                    bMoveAncestorMoved(evt);
                }
                public void ancestorResized(java.awt.event.HierarchyEvent evt) {
                }
            });

            bI.setBackground(java.awt.SystemColor.text);
            bI.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bI.setText("i");
            bI.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bIActionPerformed(evt);
                }
            });

            bO.setBackground(java.awt.SystemColor.text);
            bO.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bO.setText("o");
            bO.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bOActionPerformed(evt);
                }
            });

            bP.setBackground(java.awt.SystemColor.text);
            bP.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bP.setText("p");
            bP.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bPActionPerformed(evt);
                }
            });

            bQ.setBackground(java.awt.SystemColor.text);
            bQ.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bQ.setText("q");
            bQ.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bQActionPerformed(evt);
                }
            });

            but3.setBackground(java.awt.SystemColor.text);
            but3.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but3.setText("[");
            but3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but3ActionPerformed(evt);
                }
            });

            but6.setBackground(java.awt.SystemColor.text);
            but6.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but6.setText(",");
            but6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but6ActionPerformed(evt);
                }
            });

            bC.setBackground(java.awt.SystemColor.text);
            bC.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bC.setText("c");
            bC.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bCActionPerformed(evt);
                }
            });

            bV.setBackground(java.awt.SystemColor.text);
            bV.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bV.setText("v");
            bV.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bVActionPerformed(evt);
                }
            });

            bZ.setBackground(java.awt.SystemColor.text);
            bZ.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bZ.setText("z");
            bZ.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bZActionPerformed(evt);
                }
            });

            bX.setBackground(java.awt.SystemColor.text);
            bX.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bX.setText("x");
            bX.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bXActionPerformed(evt);
                }
            });

            bShift.setBackground(java.awt.SystemColor.text);
            bShift.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bShift.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/paracel/pos/images/ark2.png"))); // NOI18N
            bShift.setText("Shift");
            bShift.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    bShiftMousePressed(evt);
                }
            });
            bShift.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bShiftActionPerformed(evt);
                }
            });

            bCaps.setBackground(java.awt.SystemColor.text);
            bCaps.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bCaps.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/paracel/pos/images/ark2.png"))); // NOI18N
            bCaps.setText("Caps");
            bCaps.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bCapsActionPerformed(evt);
                }
            });

            but7.setBackground(java.awt.SystemColor.text);
            but7.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but7.setText(".");
            but7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but7ActionPerformed(evt);
                }
            });

            bSpace.setBackground(java.awt.SystemColor.text);
            bSpace.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bSpace.setText("SPACE");
            bSpace.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bSpaceActionPerformed(evt);
                }
            });

            bA.setBackground(java.awt.SystemColor.text);
            bA.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bA.setText("a");
            bA.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bAActionPerformed(evt);
                }
            });

            bS.setBackground(java.awt.SystemColor.text);
            bS.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bS.setText("s");
            bS.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bSActionPerformed(evt);
                }
            });

            bG.setBackground(java.awt.SystemColor.text);
            bG.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bG.setText("g");
            bG.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bGActionPerformed(evt);
                }
            });

            bH.setBackground(java.awt.SystemColor.text);
            bH.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bH.setText("h");
            bH.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bHActionPerformed(evt);
                }
            });

            bD.setBackground(java.awt.SystemColor.text);
            bD.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bD.setText("d");
            bD.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bDActionPerformed(evt);
                }
            });

            bF.setBackground(java.awt.SystemColor.text);
            bF.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bF.setText("f");
            bF.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bFActionPerformed(evt);
                }
            });

            but8.setBackground(java.awt.SystemColor.text);
            but8.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but8.setText("/");
            but8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but8ActionPerformed(evt);
                }
            });

            bN.setBackground(java.awt.SystemColor.text);
            bN.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bN.setText("n");
            bN.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bNActionPerformed(evt);
                }
            });

            bB.setBackground(java.awt.SystemColor.text);
            bB.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bB.setText("b");
            bB.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bBActionPerformed(evt);
                }
            });

            bM.setBackground(java.awt.SystemColor.text);
            bM.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bM.setText("m");
            bM.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bMActionPerformed(evt);
                }
            });

            bEnter.setBackground(java.awt.SystemColor.text);
            bEnter.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bEnter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/paracel/pos/images/button_ok.png"))); // NOI18N
            bEnter.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bEnterActionPerformed(evt);
                }
            });

            b9.setBackground(java.awt.SystemColor.text);
            b9.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b9.setText("9");
            b9.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b9ActionPerformed(evt);
                }
            });

            b0.setBackground(java.awt.SystemColor.text);
            b0.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b0.setText("0");
            b0.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b0ActionPerformed(evt);
                }
            });

            bBackSpace.setBackground(java.awt.SystemColor.text);
            bBackSpace.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            bBackSpace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vn/paracel/pos/images/locationbar_erase-02.png"))); // NOI18N
            bBackSpace.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    bBackSpaceActionPerformed(evt);
                }
            });

            but1.setBackground(java.awt.SystemColor.text);
            but1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but1.setText("-");
            but1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but1ActionPerformed(evt);
                }
            });

            but2.setBackground(java.awt.SystemColor.text);
            but2.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            but2.setText("+");
            but2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    but2ActionPerformed(evt);
                }
            });

            b1.setBackground(java.awt.SystemColor.text);
            b1.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b1.setText("1");
            b1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b1ActionPerformed(evt);
                }
            });

            b6.setBackground(java.awt.SystemColor.text);
            b6.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b6.setText("6");
            b6.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b6ActionPerformed(evt);
                }
            });

            b8.setBackground(java.awt.SystemColor.text);
            b8.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b8.setText("8");
            b8.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b8ActionPerformed(evt);
                }
            });

            b4.setBackground(java.awt.SystemColor.text);
            b4.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b4.setText("4");
            b4.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b4ActionPerformed(evt);
                }
            });

            b7.setBackground(java.awt.SystemColor.text);
            b7.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b7.setText("7");
            b7.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b7ActionPerformed(evt);
                }
            });

            b5.setBackground(java.awt.SystemColor.text);
            b5.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b5.setText("5");
            b5.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b5ActionPerformed(evt);
                }
            });

            b3.setBackground(java.awt.SystemColor.text);
            b3.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b3.setText("3");
            b3.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b3ActionPerformed(evt);
                }
            });

            b2.setBackground(java.awt.SystemColor.text);
            b2.setFont(new java.awt.Font("Ubuntu Mono", 1, 18)); // NOI18N
            b2.setText("2");
            b2.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    b2ActionPerformed(evt);
                }
            });

            jButton1.setText("Clode");
            jButton1.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
                }
            });

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(7, 7, 7)
                            .addComponent(bE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(4, 4, 4)
                            .addComponent(bR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(7, 7, 7)
                            .addComponent(bY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(39, 39, 39)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(28, 28, 28)
                            .addComponent(bA, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bS, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bD, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bF, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bG, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bH, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bJ, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bK, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bL, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bMove, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(50, 50, 50)
                            .addComponent(bZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(but8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bEnter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(bCaps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(12, 12, 12)
                            .addComponent(bShift, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(but1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(but2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(bBackSpace, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(but3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bW, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bY, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(but4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bMove, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(bS, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(bD, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(bF, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(bA, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(but5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bZ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(but8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bCaps, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bSpace, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bShift, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            );

            jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {b8, b9});

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            pack();
        }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       
         fulltext = activeTextField.getText() + b1.getText();
         activeTextField.setText( fulltext );
         ChangeNum(evt);
        
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b2.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b3.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b3ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b4.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b5.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b6.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b7.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b8.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b9.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b9ActionPerformed

    private void b0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b0ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + b0.getText();
        activeTextField.setText(fulltext);
        ChangeNum(evt);
    }//GEN-LAST:event_b0ActionPerformed

    private void bQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQActionPerformed
        // TODO add your handling code here:
       fulltext = activeTextField.getText() + bQ.getText();
       activeTextField.setText(fulltext);
       ChangeButton(evt);
       ChangeNum(evt);
        
    }//GEN-LAST:event_bQActionPerformed

    private void bWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bWActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bW.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bWActionPerformed

    private void bEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bE.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bEActionPerformed

    private void bRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bR.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bRActionPerformed

    private void bTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bT.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bTActionPerformed

    private void bYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bYActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bY.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bYActionPerformed

    private void bUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bUActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bU.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bUActionPerformed

    private void bIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bI.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bIActionPerformed

    private void bOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bO.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bOActionPerformed

    private void bPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bP.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bPActionPerformed

    private void bAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bA.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bAActionPerformed

    private void bSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bS.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bSActionPerformed

    private void bDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bD.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bDActionPerformed

    private void bFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bF.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bFActionPerformed

    private void bGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bG.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bGActionPerformed

    private void bHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bH.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bHActionPerformed

    private void bJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bJActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bJ.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bJActionPerformed

    private void bKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bKActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bK.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bKActionPerformed

    private void bLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bL.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bLActionPerformed

    private void bEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEnterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_bEnterActionPerformed

    private void bZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bZActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bZ.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bZActionPerformed

    private void bXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bXActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bX.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bXActionPerformed

    private void bCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bC.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bCActionPerformed

    private void bVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bV.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bVActionPerformed

    private void bBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bB.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bBActionPerformed

    private void bNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bN.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bNActionPerformed

    private void bSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSpaceActionPerformed
        // TODO add your handling code here:
        //substring lay ra index trong chuoi string
        fulltext = activeTextField.getText() + " ";
        //text.setText(fulltext.substring(0, fulltext.length()-1));
        activeTextField.setText(fulltext);
        
        
    }//GEN-LAST:event_bSpaceActionPerformed

    private void bBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBackSpaceActionPerformed
        // TODO add your handling code here:
        try {
            fulltext = activeTextField.getText();
            if (fulltext.length() > 0){
                activeTextField.setText(fulltext.substring(0, fulltext.length()-1));
            }
        }
        catch (IndexOutOfBoundsException e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bBackSpaceActionPerformed
    private void ChangeButton(ActionEvent evt){
        JButton[] listButton={
            bA,
            bQ,
            bW,
            bE,
            bR,
            bT,
            bY,
            bU,
            bI,
            bO,
            bP,
            bS,
            bD,
            bF,
            bG,
            bH,
            bJ,
            bK,
            bL,
            bZ,
            bX,
            bC,
            bV,
            bB,
            bN,
            bM,
        };
        for (int i= 0; i<listButton.length; i++){
                    if (listButton[i].getText().hashCode() >= 65 && listButton[i].getText().hashCode() <=96 ) {
                    //System.out.println(listButton[i].getText().toUpperCase());
                    listButton[i].setText(listButton[i].getText().toLowerCase());
                    //System.out.println(listButton[i].getText().hashCode());
                }
        }
        
    
    }
    private void bCapsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCapsActionPerformed
        // TODO add your handling code here:
        // Add cac button vao 1 mang
        JButton[] listButton={
            bA,
            bQ,
            bW,
            bE,
            bR,
            bT,
            bY,
            bU,
            bI,
            bO,
            bP,
            bS,
            bD,
            bF,
            bG,
            bH,
            bJ,
            bK,
            bL,
            bZ,
            bX,
            bC,
            bV,
            bB,
            bN,
            bM,
        };
            // dung method loLowerCase() de chuyen ky tu hoa sang ky tu thuong
            for (int i= 0; i<listButton.length; i++){
                    if (listButton[i].getText().hashCode() >= 97 && listButton[i].getText().hashCode() <=122 ) {
                    //System.out.println(listButton[i].getText().toLowerCase());
                    listButton[i].setText(listButton[i].getText().toUpperCase());
                    //System.out.println(listButton[i].getText().hashCode());
                    }
                    else if (listButton[i].getText().hashCode() >= 65 && listButton[i].getText().hashCode() <=96 ) {
                    //System.out.println(listButton[i].getText().toUpperCase());
                    listButton[i].setText(listButton[i].getText().toLowerCase());
                    //System.out.println(listButton[i].getText().hashCode());
                }
        }
        
        
        
        
        
        
    }//GEN-LAST:event_bCapsActionPerformed

    private void bMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + bM.getText();
        activeTextField.setText(fulltext);
        ChangeButton(evt);
        ChangeNum(evt);
    }//GEN-LAST:event_bMActionPerformed

    private void bShiftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bShiftActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bShiftActionPerformed

    private void but6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but6ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + but6.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but6ActionPerformed

    private void but7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but7ActionPerformed
        // TODO add your handling code here:
        fulltext = activeTextField.getText() + but7.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but7ActionPerformed

    private void bShiftMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bShiftMousePressed
        b1.setText("!");
        b2.setText("@");
        b3.setText("#");
        b4.setText("$");
        b5.setText("%");
        b6.setText("^");
        b7.setText("&");
        b8.setText("*");
        b9.setText("(");
        b0.setText(")");
        
        but1.setText("_");
        but2.setText("+");
        but3.setText("{");
        
        but4.setText("}");
        
        but5.setText(":");
        but6.setText("<");
        
        but7.setText(">");
        but8.setText("?");
        JButton[] listButton={
            bA,
            bQ,
            bW,
            bE,
            bR,
            bT,
            bY,
            bU,
            bI,
            bO,
            bP,
            bS,
            bD,
            bF,
            bG,
            bH,
            bJ,
            bK,
            bL,
            bZ,
            bX,
            bC,
            bV,
            bB,
            bN,
            bM,
        };
            // dung method loLowerCase() de chuyen ky tu hoa sang ky tu thuong
            for (int i= 0; i<listButton.length; i++){
                    if (listButton[i].getText().hashCode() >= 97 && listButton[i].getText().hashCode() <=122 ) {
                    //System.out.println(listButton[i].getText().toLowerCase());
                    listButton[i].setText(listButton[i].getText().toUpperCase());
                    //System.out.println(listButton[i].getText().hashCode());
                    }
                    else if (listButton[i].getText().hashCode() >= 65 && listButton[i].getText().hashCode() <=96 ) {
                    //System.out.println(listButton[i].getText().toUpperCase());
                    listButton[i].setText(listButton[i].getText().toLowerCase());
                    //System.out.println(listButton[i].getText().hashCode());
                }
        }
        
    }//GEN-LAST:event_bShiftMousePressed

    private void bMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bMoveActionPerformed
        fulltext = activeTextField.getText() + bMove.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_bMoveActionPerformed

    private void bMoveMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bMoveMouseMoved
        
    }//GEN-LAST:event_bMoveMouseMoved

    private void but8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but8ActionPerformed
        fulltext = activeTextField.getText() + but8.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but8ActionPerformed

    private void but5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but5ActionPerformed
        fulltext = activeTextField.getText() + but5.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but5ActionPerformed

    private void but3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but3ActionPerformed
        fulltext = activeTextField.getText() + but3.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but3ActionPerformed

    private void but4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but4ActionPerformed
        fulltext = activeTextField.getText() + but4.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but4ActionPerformed

    private void but1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but1ActionPerformed
        fulltext = activeTextField.getText() + but1.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but1ActionPerformed

    private void but2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_but2ActionPerformed
        fulltext = activeTextField.getText() + but2.getText();
        activeTextField.setText( fulltext );
        ChangeNum(evt);
    }//GEN-LAST:event_but2ActionPerformed

    private void bMoveAncestorMoved(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_bMoveAncestorMoved
    }//GEN-LAST:event_bMoveAncestorMoved

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed
    private void ChangeNum(ActionEvent evt){
        b1.setText("1");
        b2.setText("2");
        b3.setText("3");
        b4.setText("4");
        b5.setText("5");
        b6.setText("6");
        b7.setText("7");
        b8.setText("8");
        b9.setText("9");
        b0.setText("0");
        
        but1.setText("-");
        but2.setText("=");
        but3.setText("[");
        but4.setText("]");
        but5.setText(";");
        but6.setText(",");
        but7.setText(".");
        but8.setText("/");
        
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b0;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton bA;
    private javax.swing.JButton bB;
    private javax.swing.JButton bBackSpace;
    private javax.swing.JButton bC;
    private javax.swing.JButton bCaps;
    private javax.swing.JButton bD;
    private javax.swing.JButton bE;
    private javax.swing.JButton bEnter;
    private javax.swing.JButton bF;
    private javax.swing.JButton bG;
    private javax.swing.JButton bH;
    private javax.swing.JButton bI;
    private javax.swing.JButton bJ;
    private javax.swing.JButton bK;
    private javax.swing.JButton bL;
    private javax.swing.JButton bM;
    private javax.swing.JButton bMove;
    private javax.swing.JButton bN;
    private javax.swing.JButton bO;
    private javax.swing.JButton bP;
    private javax.swing.JButton bQ;
    private javax.swing.JButton bR;
    private javax.swing.JButton bS;
    private javax.swing.JButton bShift;
    private javax.swing.JButton bSpace;
    private javax.swing.JButton bT;
    private javax.swing.JButton bU;
    private javax.swing.JButton bV;
    private javax.swing.JButton bW;
    private javax.swing.JButton bX;
    private javax.swing.JButton bY;
    private javax.swing.JButton bZ;
    private javax.swing.JButton but1;
    private javax.swing.JButton but2;
    private javax.swing.JButton but3;
    private javax.swing.JButton but4;
    private javax.swing.JButton but5;
    private javax.swing.JButton but6;
    private javax.swing.JButton but7;
    private javax.swing.JButton but8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton30;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
